apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-league-service
  labels:
    app: faf-league-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-league-service
  template:
    metadata:
      labels:
        app: faf-league-service
    spec:
      containers:
        - image: faforever/faf-league-service:1.5.0
          name: faf-league-service
          envFrom:
            - configMapRef:
                name: faf-league-service
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-league-service
  labels:
    app: faf-league-service
data:
  DB_SERVER: faf-db
  DB_PORT: "3306"
  DB_LOGIN: "faf-league-service"
  DB_PASSWORD: "banana"
  DB_NAME: "faf-league"
  AUTO_APPLY_MIGRATIONS: "1"

  MQ_USER: faf-league-service
  MQ_PASSWORD: "banana"
  MQ_SERVER: rabbitmq
  MQ_PORT: "5672"
  MQ_VHOST: /faf-core
  MQ_PREFETCH_COUNT: "300"

  EXCHANGE_NAME: faf-lobby
  TRUESKILL_RATING_UPDATE_ROUTING_KEY: success.rating.update
  LEAGUE_SCORE_UPDATE_ROUTING_KEY: success.leagueScore.update
  LEAGUE_SCORE_UPDATE_FAIL_ROUTING_KEY: failure.leagueScore.update

  SEASON_GENERATION_DAYS_BEFORE_SEASON_END: "14"
  SEASON_LENGTH_MONTHS: "3"
  RATING_MODIFIER_FOR_PLACEMENT: "0"
  SCORE_GAIN: "1"
  POSITIVE_BOOST: "1"
  NEGATIVE_BOOST: "1"
  HIGHEST_DIVISION_BOOST: "1"
  POINT_BUFFER_AFTER_DIVISION_CHANGE: "2"