apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-api
  labels:
    app: faf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-api
  template:
    metadata:
      labels:
        app: faf-api
    spec:
      containers:
        - image: faforever/faf-java-api:v3.4.5
          name: faf-api
          envFrom:
            - configMapRef:
                name: faf-api
          ports:
            - containerPort: 8010
            - name: management-port
              containerPort: 8011
          volumeMounts:
            - name: faf-api-pki
              mountPath: /pki
            - name: mail-templates
              mountPath: /config/mail/
              readOnly: true
          startupProbe:
            httpGet:
              port: management-port
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: management-port
              path: /actuator/health
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: faf-api-pki
          projected:
            sources:
              - configMap:
                  name: faf-api
                  items:
                    - key: PUBLIC.KEY
                      path: public.key
                    - key: SECRET.KEY
                      path: secret.key
            defaultMode: 440
        - name: mail-templates
          configMap:
            name: faf-user-service-mail-templates

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-api
  labels:
    app: faf-api
data:
  FAF_DOMAIN: "localhost"
  JAVA_TOOL_OPTIONS: "-Xms512m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"

  # App options
  JWT_FAF_HYDRA_ISSUER: "http://ory-hydra:4444/"
  DATABASE_ADDRESS: "faf-db"
  DATABASE_NAME: "faf"
  DATABASE_USERNAME: "faf-java-api"
  DATABASE_PASSWORD: "banana"
  EMAIL_FROM_ADDRESS: "admin@faforever.com"
  EMAIL_FROM_NAME: "FAForever"
  GITHUB_DEPLOYMENT_ENVIRONMENT: "development"
  LEAGUE_DATABASE_ADDRESS: "faf-db"
  LEAGUE_DATABASE_NAME: "faf_league"
  LEAGUE_DATABASE_USERNAME: "faf-java-api"
  LEAGUE_DATABASE_PASSWORD: "banana"
  NODEBB_BASE_URL: "http://nodebb:4567"
  NODEBB_USER_ID: "1"
  RECAPTCHA_ENABLED: "true"
  RABBIT_HOST: "rabbitmq"
  RABBIT_USERNAME: "faf-api"
  RABBIT_PASSWORD: "banana"
  REPLAY_DOWNLOAD_URL_FORMAT: http://localhost:8000/replays/%s
  GITHUB_ACCESS_TOKEN: "false"
  GITHUB_WEBHOOK_SECRET: "false"
  API_PROFILE: "develop"
  SECRET.KEY: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpgIBAAKCAQEAzTpJ/ytBu3dih41bEqRnchNfkyCigIWDHrbBa+0Szw853Oew
      LJ1Zwe5wh9L8nxWD7f+pVDg5dAKXAJabmx6vuXhJjekIxrHTIRdxebO2norhAK/Q
      OuOZ4NKinShpWwyLgmPcJZaKq1TNtVm7No/3CQK5XugDJ5NG2c1RNEAdk3pk2EkB
      lhhObJW2vUY+KmJ+4ndwZKeyJD4CTr4sJK7cWRf2Ht2RWq6omFlsnQiPGyO9/VYo
      YQz3fVTiXdf4+xg6toBaVvult0YPS5/jm611RrsMwLM4ZpWkUlytxR/N8/oLb9rD
      nO9+OQZDpIsKfNd3ZAqg/wZTHIcb474UHjUTiQIDAQABAoIBAQCMuO1IZNbbvs72
      97x9GfI8zH/6mKQU0HfKNbKHWLZO+LfKe6vXy8ViLydGWywRwWUHawkm0K7El4oH
      Qz5LrUz9NjfpcOMtq32D8VlEBDCyobQLDoMP/kTjXktWzAECB6YZsHOh6ooHVU0A
      jxjKHwlbSlzlcN3I4znv2tNVqqkdF9Gbg7wUmN9n0qpj+7kDtkixJy3jm9YLxKCS
      pNZ1UUjGKtVgl/1871slNUtANHj/xCnkYrOncrIXf472pEeSxBU5JlI4fILcyTtG
      B9btuYBk7Z239TWDEZTqIyst0QGteNRsjE+gkB9WV1ra9JPPWDiBYye4qqaIs3al
      jd3lkMApAoGBAP+i1aJ/c8XV18eTMYLmQZRnkjrkxyQMhJ/x+6tow6p6A16lDwHh
      tRoyQk0XdTpQegu+YtdBXSRk6zNzE2njWEVOMK4/Zqt5a1yMSE/8MMQVler1ChdF
      PWhZCPb+CfKm1RHXpFMsmBZx+7MumLQwjCtZfQl8YMt34gfVcXRSZ50DAoGBAM2F
      FVrTTUVaGv6zjdO7K+5eUj0VRR2nGId5nIWqouQryJaizeBZfWatjDYVbl0qHFy2
      QnHA+3UEsVWOkJG90rZcP4UWcDy86e5T/3FR2Xfy3kW10Gfe6hrjjbjYflleD5Qg
      uZ9ovk/TZjTjvMWisNBSW1FILz9SMLWHoCFPGOmDAoGBANKRb4X1lAiOt7n13d+k
      CLrUgVgvoHVqNkiFi7dKiXnAHUx1i6ISKBoW8hQMUYyiQ5Wu0j3a4n0a/74WeRRM
      pyYXXPP613hBgJTwHJR9+DFcUmwCQbifWRC93iuNX+ZXU8Tpqrq0TeaXJywWIsSy
      BJOkl+EbaaPP8Qhg4Z5eTmi/AoGBAMzSDyA/acjuLe0cwQH8jaG3+rnJkuIkf3u0
      pVtJXaGMSRJnGkq2pRVJbG0SGrVanH2BXuLDc1eB38HmnQnCZlc7xEo8vIqrs2/D
      4tXqvpKeRwquUg7Sx/kYQ0uu5uzloxz7KENIPjKL+lZHiQBmTVSwXzW4fO3cWZLw
      oZPQooFFAoGBAMVvhsOmlpwyyS9s/CVIMirvLQEuEIIS5fMcnmCmu8P49ZZ7YSVf
      2OJOSGj+lWkEMf2qOW7kYl303GrESeJ36KmLbDthnH+p6RSq5NzN5CAucffA0tsa
      keX0a6YHVu9doUPhUFJdbgg8FIL1FVEJROQckMAiDcYg2mFXmtaVTjqX
      -----END RSA PRIVATE KEY-----
  PUBLIC.KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNOkn/K0G7d2KHjVsSpGdyE1+TIKKAhYMetsFr7RLPDznc57AsnVnB7nCH0vyfFYPt/6lUODl0ApcAlpubHq+5eEmN6QjGsdMhF3F5s7aeiuEAr9A645ng0qKdKGlbDIuCY9wlloqrVM21Wbs2j/cJArle6AMnk0bZzVE0QB2TemTYSQGWGE5slba9Rj4qYn7id3Bkp7IkPgJOviwkrtxZF/Ye3ZFarqiYWWydCI8bI739VihhDPd9VOJd1/j7GDq2gFpW+6W3Rg9Ln+ObrXVGuwzAszhmlaRSXK3FH83z+gtv2sOc7345BkOkiwp813dkCqD/BlMchxvjvhQeNROJ api@faforever.com"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-api-mail-templates
  labels:
    app: faf-api-mail-templates
data:
  "account-activation.html": "{{username}} {{activationUrl}}"
  "password-reset.html": "{{username}} {{passwordResetUrl}}"
  "welcome-to-faf.html": "{{username}}"

---
apiVersion: v1
kind: Service
metadata:
  name: faf-api
  labels:
    app: faf-api
spec:
  selector:
    app: faf-api
  ports:
    - port: 8010
      targetPort: 8010