apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.13.3-management-alpine
          imagePullPolicy: Always
          name: rabbitmq
          envFrom:
            - configMapRef:
                name: rabbitmq
          ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 15672
              name: webinterface
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: rabbitmq

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
data:
  ADMIN_USER: "faf-admin"
  ADMIN_PASSWORD: "banana"
  FAF_API_PASSWORD: "banana"
  PYTHON_SERVER_PASSWORD: "banana"
  LEAGUE_SERVICE_PASSWORD: "banana"
  "enabled_plugins": "[rabbitmq_management]."

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672